cmdHelp: "&dИспользуй: /cforbidden <args>"
cmdRelod: "&aПерезагрузка файла конфигурации выполнена..."
defaultMsg: "&6Неизвестная команда! &c/help &e- для получения справки."
forbidden:
    /pl:
        message: "&6Разрешение у админа спросил на просмотр списка?"
    /op admin:
        message: "&6Он уже, спасибо за беспокойство!"
    /deop admin:
        message: "&6Админ был, есть и останется с опкой!"
    /pex group:
        message: "&6Чтобы повысить игроку ранг, используй команду: &a/promote <ник игрока>"
    /pex: []
    /promote:
        args: true
        message: "&6Кто счастлифчик? Используй: &a/promote <ник игрока>"
    /nocheatplus: []
